name: Swift

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    # Hack around XCode 11 issue
    - run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
    - uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: Rust.xcodeproj
        scheme: Rust
        destination: platform=macOS
        action: test
